- name: Remove Kubernetes apt repository key file
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: Remove Kubernetes repository source file
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Update apt cache
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Set containerd default config
  command: containerd config default
  register: containerd_default_config

- name: Write containerd config to file
  copy:
    content: "{{ containerd_default_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Enable SystemdCgroup in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup = )false$'
    replace: '\1true'

- name: Use pause image 3.9
  shell: sed -i 's#sandbox_image = "registry\.k8s\.io/pause:3\.8"#sandbox_image = "registry.k8s.io/pause:3.9"#' /etc/containerd/config.toml

- name: Enable IPv4 forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^#net\.ipv4\.ip_forward=1$'
    replace: 'net.ipv4.ip_forward=1'

- name: Add br_netfilter to modules-load.d
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: 'br_netfilter'
    create: yes
    state: present

- name: Reboot the system
  reboot:
    reboot_timeout: 200
    pre_reboot_delay: 30
  async: 0
  poll: 0
  ignore_errors: true

- name: Disable swap for the current session
  command: swapoff -a
  ignore_errors: true 

- name: Create the directory
  file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: Install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates
    state: present

- name : add kubernetes repo
  shell: wget -qO- https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --batch --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name : add kubernetes repo
  raw: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Install Kubernetes tools
  apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present
    update_cache: yes