- name: Run kubeadm init
  command: >
    kubeadm init --node-name={{ansible_hostname}} --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all --control-plane-endpoint={{privatelbip}}:6443

- name: create .kube directory
  file:
    path: .kube
    state: directory
    owner: ubuntu
    group: ubuntu

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu

# - name: Download custom-resources.yaml using curl
#   shell: curl -o /tmp/calico.yaml https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
#   become_user: ubuntu
#   become: true

# - name: Apply Calico resources
#   shell: kubectl create -f /tmp/calico.yaml 
#   become_user: ubuntu
#   become: true


- name: Download Cilium CLI
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable-v0.14.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
    rm cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
  args:
    chdir: /tmp
  changed_when: false

- name: Install Cilium
  shell: "cilium install --ipam kubernetes"
  become_user: ubuntu
  become: true

