- name: Execute kubeadm join command
  shell: "{{ hostvars[groups['master'][0]]['join_command_control_node'] }} --ignore-preflight-errors=all"

- name: create .kube directory
  file:
    path: .kube
    state: directory
    owner: ubuntu
    group: ubuntu

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu