- name: End Play Gracefully when already part of cluster
  meta: end_play
  when: hostvars[groups['master'][0]]['node_names'] is defined and inventory_hostname in hostvars[groups['master'][0]]['node_names']
  ignore_errors: true

- name: Execute kubeadm join command
  shell: "{{ hostvars[groups['master'][0]]['join_command'] }} --control-plane --certificate-key {{ hostvars[groups['master'][0]]['join_certs'] }} --ignore-preflight-errors=all"

- name: create .kube directory
  file:
    path: .kube
    state: directory
    mode: 0755
    owner: ubuntu

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes
    owner: ubuntu