- name: Setup Containerd and Kubernetes tools
  hosts: master
  become: true
  roles:
    - clusterprereq

- name: Initialize Kubernetes Master Node
  hosts: master
  become: true
  roles:
    - initializemaster

- name: Get Join Key From Master 
  hosts: master
  become: true
  roles:
    - getjoinkey

- name: Setup Containerd and Kubernetes tools on Control Node
  hosts: [joinasworker,joinasmaster]
  become: true
  roles:
    - clusterprereq

- name: Join Worker Node to the Cluster
  hosts: joinasworker
  become: true
  roles:
    - joinworker

- name: Add Control Node to Cluster
  hosts: joinasmaster
  become: true
  roles:
    - joinmaster
