- name: Setup Containerd and Kubernetes tools
  hosts: master
  become: true
  roles:
    - clusterprereq

- name: Initialize Kubernetes Master Node
  hosts: master
  become: true
  roles:
    - initializemaster

- name: Get Join Key From Master 
  hosts: master
  become: true
  roles:
    - getjoinkey

- name: Setup Containerd and Kubernetes tools other Nodes
  hosts: [joinasworker,joinasmaster]
  become: true
  roles:
    - clusterprereq

- name: Join Worker Node to the Cluster
  hosts: joinasworker
  become: true
  roles:
    - joinworker

- name: Add Control Node to Cluster
  hosts: joinasmaster
  become: true
  roles:
    - joinmaster

# - name: Add Istio Mesh
#   hosts: master
#   become: true
#   become_user: ubuntu
#   vars:
#     istio_version: "1.19.1"
#     target_arch_mapping:
#       x86_64: x86_64
#       aarch64: arm64
#   roles:
#     - addistiomesh

- name: Add Ingress Nginx
  hosts: master
  become: true
  become_user: ubuntu
  roles:
    - addnginxingress