- name: get join token control node
  shell: echo $(kubeadm token create --print-join-command) --control-plane --certificate-key $(kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace)
  register: join_command_control_node_raw

- name: get join token worker
  shell: kubeadm token create --print-join-command
  register: join_command_worker_raw

- name: set facts
  set_fact:
    join_command_control_node: "{{ join_command_control_node_raw.stdout_lines[0] }}"
    join_command_worker_node: "{{ join_command_worker_raw.stdout_lines[0] }}"