- name: Run kubectl get nodes on remote hosts
  shell: kubectl get nodes --no-headers 
  become_user: ubuntu
  register: kubectl_output

- name: get join token
  shell: kubeadm token create --print-join-command
  register: join_command_raw 

- name: get join certifactes
  shell: kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace
  register: join_certs_raw

- name: set facts
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
    join_certs: "{{ join_certs_raw.stdout_lines[0] }}"
    node_names: "{{ kubectl_output.stdout_lines | map('split') | map(attribute='0') | list }}"